// This file is auto-generated by @hey-api/openapi-ts

export const $AchievementSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Name of the achievement.'
        },
        code: {
            type: 'string',
            title: 'Code',
            description: 'Code of the achievement. '
        },
        description: {
            type: 'string',
            title: 'Description',
            description: 'Description of the achievement.'
        },
        points: {
            type: 'integer',
            title: 'Points',
            description: 'Points of the achievement. Used for the leaderboard.'
        },
        type: {
            type: 'string',
            enum: ['combat_kill', 'combat_drop', 'combat_level', 'gathering', 'crafting', 'recycling', 'task', 'other'],
            title: 'Type',
            description: 'Type of achievement.'
        },
        target: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target',
            description: 'Target of the achievement.'
        },
        total: {
            type: 'integer',
            title: 'Total',
            description: 'Total to do.'
        },
        current: {
            type: 'integer',
            title: 'Current',
            description: 'Current progress.'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At',
            description: 'Completed at.'
        }
    },
    type: 'object',
    required: ['name', 'code', 'description', 'points', 'type', 'target', 'total', 'current', 'completed_at'],
    title: 'AchievementSchema'
} as const;

export const $ActiveEventSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Name of the event.'
        },
        map: {
            allOf: [
                {
                    '$ref': '#/components/schemas/MapSchema'
                }
            ],
            description: 'Map of the event.'
        },
        previous_skin: {
            type: 'string',
            title: 'Previous Skin',
            description: 'Previous map skin.'
        },
        duration: {
            type: 'integer',
            title: 'Duration',
            description: 'Duration in minutes.'
        },
        expiration: {
            type: 'string',
            format: 'date-time',
            title: 'Expiration',
            description: 'Expiration datetime.'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: 'Start datetime.'
        }
    },
    type: 'object',
    required: ['name', 'map', 'previous_skin', 'duration', 'expiration', 'created_at'],
    title: 'ActiveEventSchema'
} as const;

export const $AddAccountSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 32,
            minLength: 6,
            pattern: '^[a-zA-Z0-9_-]+$',
            title: 'Username',
            description: 'Your desired username.'
        },
        password: {
            type: 'string',
            maxLength: 50,
            minLength: 5,
            pattern: '^[^\\s]+$',
            title: 'Password',
            description: 'Your password.'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email',
            description: 'Your email.'
        }
    },
    type: 'object',
    required: ['username', 'password', 'email'],
    title: 'AddAccountSchema'
} as const;

export const $AddCharacterSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 12,
            minLength: 3,
            pattern: '^[a-zA-Z0-9_-]+$',
            title: 'Name',
            description: "Your desired character name. It's unique and all players can see it."
        },
        skin: {
            type: 'string',
            enum: ['men1', 'men2', 'men3', 'women1', 'women2', 'women3'],
            title: 'Skin',
            description: 'Your desired skin.'
        }
    },
    type: 'object',
    required: ['name', 'skin'],
    title: 'AddCharacterSchema'
} as const;

export const $AnnouncementSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message',
            description: 'Announcement text.'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: 'Datetime of the announcement.'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'AnnouncementSchema'
} as const;

export const $BankExtensionSchema = {
    properties: {
        price: {
            type: 'integer',
            minimum: 0,
            title: 'Price',
            description: 'Price of the bank extension.'
        }
    },
    type: 'object',
    required: ['price'],
    title: 'BankExtensionSchema'
} as const;

export const $BankExtensionTransactionResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/BankExtensionTransactionSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'BankExtensionTransactionResponseSchema'
} as const;

export const $BankExtensionTransactionSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details.'
        },
        transaction: {
            allOf: [
                {
                    '$ref': '#/components/schemas/BankExtensionSchema'
                }
            ],
            description: 'Transaction details.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Player details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'transaction', 'character'],
    title: 'BankExtensionTransactionSchema'
} as const;

export const $BankGoldTransactionResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/BankGoldTransactionSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'BankGoldTransactionResponseSchema'
} as const;

export const $BankGoldTransactionSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details.'
        },
        bank: {
            allOf: [
                {
                    '$ref': '#/components/schemas/GoldSchema'
                }
            ],
            description: 'Bank details.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Player details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'bank', 'character'],
    title: 'BankGoldTransactionSchema'
} as const;

export const $BankItemTransactionResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/BankItemTransactionSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'BankItemTransactionResponseSchema'
} as const;

export const $BankItemTransactionSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details.'
        },
        item: {
            allOf: [
                {
                    '$ref': '#/components/schemas/ItemSchema'
                }
            ],
            description: 'Item details.'
        },
        bank: {
            items: {
                '$ref': '#/components/schemas/SimpleItemSchema'
            },
            type: 'array',
            title: 'Bank',
            description: 'Items in your banks.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Player details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'item', 'bank', 'character'],
    title: 'BankItemTransactionSchema'
} as const;

export const $BankResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/BankSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'BankResponseSchema'
} as const;

export const $BankSchema = {
    properties: {
        slots: {
            type: 'integer',
            minimum: 0,
            title: 'Slots',
            description: 'Maximum slots in your bank.'
        },
        expansions: {
            type: 'integer',
            minimum: 0,
            title: 'Expansions',
            description: 'Bank expansions.'
        },
        next_expansion_cost: {
            type: 'integer',
            minimum: 0,
            title: 'Next Expansion Cost',
            description: 'Next expansion cost.'
        },
        gold: {
            type: 'integer',
            minimum: 0,
            title: 'Gold',
            description: 'Quantity of gold in your bank.'
        }
    },
    type: 'object',
    required: ['slots', 'expansions', 'next_expansion_cost', 'gold'],
    title: 'BankSchema'
} as const;

export const $BaseAchievementSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Name of the achievement.'
        },
        code: {
            type: 'string',
            title: 'Code',
            description: 'Code of the achievement. '
        },
        description: {
            type: 'string',
            title: 'Description',
            description: 'Description of the achievement.'
        },
        points: {
            type: 'integer',
            title: 'Points',
            description: 'Points of the achievement. Used for the leaderboard.'
        },
        type: {
            type: 'string',
            enum: ['combat_kill', 'combat_drop', 'combat_level', 'gathering', 'crafting', 'recycling', 'task', 'other'],
            title: 'Type',
            description: 'Type of achievement.'
        },
        target: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target',
            description: 'Target of the achievement.'
        },
        total: {
            type: 'integer',
            title: 'Total',
            description: 'Total to do.'
        }
    },
    type: 'object',
    required: ['name', 'code', 'description', 'points', 'type', 'target', 'total'],
    title: 'BaseAchievementSchema'
} as const;

export const $BaseachievementResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/BaseAchievementSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'BaseachievementResponseSchema'
} as const;

export const $BlockedHitsSchema = {
    properties: {
        fire: {
            type: 'integer',
            title: 'Fire',
            description: 'The amount of fire hits blocked.'
        },
        earth: {
            type: 'integer',
            title: 'Earth',
            description: 'The amount of earth hits blocked.'
        },
        water: {
            type: 'integer',
            title: 'Water',
            description: 'The amount of water hits blocked.'
        },
        air: {
            type: 'integer',
            title: 'Air',
            description: 'The amount of air hits blocked.'
        },
        total: {
            type: 'integer',
            title: 'Total',
            description: 'The amount of total hits blocked.'
        }
    },
    type: 'object',
    required: ['fire', 'earth', 'water', 'air', 'total'],
    title: 'BlockedHitsSchema'
} as const;

export const $ChangePassword = {
    properties: {
        password: {
            type: 'string',
            maxLength: 50,
            minLength: 5,
            pattern: '^[^\\s]+$',
            title: 'Password',
            description: 'Your password.'
        }
    },
    type: 'object',
    required: ['password'],
    title: 'ChangePassword'
} as const;

export const $CharacterFightDataSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details.'
        },
        fight: {
            allOf: [
                {
                    '$ref': '#/components/schemas/FightSchema'
                }
            ],
            description: 'Fight details.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Player details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'fight', 'character'],
    title: 'CharacterFightDataSchema'
} as const;

export const $CharacterFightResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/CharacterFightDataSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'CharacterFightResponseSchema'
} as const;

export const $CharacterLeaderboardSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Character name.'
        },
        skin: {
            type: 'string',
            title: 'Skin',
            description: 'Character skin code.'
        },
        achievements_points: {
            type: 'integer',
            title: 'Achievements Points',
            description: 'Achievements points.'
        },
        level: {
            type: 'integer',
            title: 'Level',
            description: 'Combat level.'
        },
        total_xp: {
            type: 'integer',
            title: 'Total Xp',
            description: 'Total XP of your character.'
        },
        mining_level: {
            type: 'integer',
            title: 'Mining Level',
            description: 'Mining level.'
        },
        mining_total_xp: {
            type: 'integer',
            title: 'Mining Total Xp',
            description: 'Mining total xp.'
        },
        woodcutting_level: {
            type: 'integer',
            title: 'Woodcutting Level',
            description: 'Woodcutting level.'
        },
        woodcutting_total_xp: {
            type: 'integer',
            title: 'Woodcutting Total Xp',
            description: 'Woodcutting total xp.'
        },
        fishing_level: {
            type: 'integer',
            title: 'Fishing Level',
            description: 'Fishing level.'
        },
        fishing_total_xp: {
            type: 'integer',
            title: 'Fishing Total Xp',
            description: 'Fishing total xp.'
        },
        weaponcrafting_level: {
            type: 'integer',
            title: 'Weaponcrafting Level',
            description: 'Weaponcrafting level.'
        },
        weaponcrafting_total_xp: {
            type: 'integer',
            title: 'Weaponcrafting Total Xp',
            description: 'Weaponcrafting total xp.'
        },
        gearcrafting_level: {
            type: 'integer',
            title: 'Gearcrafting Level',
            description: 'Gearcrafting level.'
        },
        gearcrafting_total_xp: {
            type: 'integer',
            title: 'Gearcrafting Total Xp',
            description: 'Gearcrafting total xp.'
        },
        jewelrycrafting_level: {
            type: 'integer',
            title: 'Jewelrycrafting Level',
            description: 'Jewelrycrafting level.'
        },
        jewelrycrafting_total_xp: {
            type: 'integer',
            title: 'Jewelrycrafting Total Xp',
            description: 'Jewelrycrafting total xp.'
        },
        cooking_level: {
            type: 'integer',
            title: 'Cooking Level',
            description: 'Cooking level.'
        },
        cooking_total_xp: {
            type: 'integer',
            title: 'Cooking Total Xp',
            description: 'Cooking total xp.'
        },
        gold: {
            type: 'integer',
            title: 'Gold',
            description: 'The numbers of golds on this character.'
        }
    },
    type: 'object',
    required: ['name', 'skin', 'achievements_points', 'level', 'total_xp', 'mining_level', 'mining_total_xp', 'woodcutting_level', 'woodcutting_total_xp', 'fishing_level', 'fishing_total_xp', 'weaponcrafting_level', 'weaponcrafting_total_xp', 'gearcrafting_level', 'gearcrafting_total_xp', 'jewelrycrafting_level', 'jewelrycrafting_total_xp', 'cooking_level', 'cooking_total_xp', 'gold'],
    title: 'CharacterLeaderboardSchema'
} as const;

export const $CharacterMovementDataSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details'
        },
        destination: {
            allOf: [
                {
                    '$ref': '#/components/schemas/MapSchema'
                }
            ],
            description: 'Destination details.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Character details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'destination', 'character'],
    title: 'CharacterMovementDataSchema'
} as const;

export const $CharacterMovementResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/CharacterMovementDataSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'CharacterMovementResponseSchema'
} as const;

export const $CharacterResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/CharacterSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'CharacterResponseSchema'
} as const;

export const $CharacterSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Name of the character.'
        },
        skin: {
            type: 'string',
            enum: ['men1', 'men2', 'men3', 'women1', 'women2', 'women3'],
            title: 'Skin',
            description: 'Character skin code.'
        },
        level: {
            type: 'integer',
            title: 'Level',
            description: 'Combat level.'
        },
        xp: {
            type: 'integer',
            title: 'Xp',
            description: 'The current xp level of the combat level.'
        },
        max_xp: {
            type: 'integer',
            title: 'Max Xp',
            description: 'XP required to level up the character.'
        },
        achievements_points: {
            type: 'integer',
            title: 'Achievements Points',
            description: 'achievements points.'
        },
        gold: {
            type: 'integer',
            title: 'Gold',
            description: 'The numbers of golds on this character.'
        },
        speed: {
            type: 'integer',
            title: 'Speed',
            description: '*Not available, on the roadmap. Character movement speed.'
        },
        mining_level: {
            type: 'integer',
            title: 'Mining Level',
            description: 'Mining level.'
        },
        mining_xp: {
            type: 'integer',
            title: 'Mining Xp',
            description: 'The current xp level of the Mining skill.'
        },
        mining_max_xp: {
            type: 'integer',
            title: 'Mining Max Xp',
            description: 'Mining XP required to level up the skill.'
        },
        woodcutting_level: {
            type: 'integer',
            title: 'Woodcutting Level',
            description: 'Woodcutting level.'
        },
        woodcutting_xp: {
            type: 'integer',
            title: 'Woodcutting Xp',
            description: 'The current xp level of the Woodcutting skill.'
        },
        woodcutting_max_xp: {
            type: 'integer',
            title: 'Woodcutting Max Xp',
            description: 'Woodcutting XP required to level up the skill.'
        },
        fishing_level: {
            type: 'integer',
            title: 'Fishing Level',
            description: 'Fishing level.'
        },
        fishing_xp: {
            type: 'integer',
            title: 'Fishing Xp',
            description: 'The current xp level of the Fishing skill.'
        },
        fishing_max_xp: {
            type: 'integer',
            title: 'Fishing Max Xp',
            description: 'Fishing XP required to level up the skill.'
        },
        weaponcrafting_level: {
            type: 'integer',
            title: 'Weaponcrafting Level',
            description: 'Weaponcrafting level.'
        },
        weaponcrafting_xp: {
            type: 'integer',
            title: 'Weaponcrafting Xp',
            description: 'The current xp level of the Weaponcrafting skill.'
        },
        weaponcrafting_max_xp: {
            type: 'integer',
            title: 'Weaponcrafting Max Xp',
            description: 'Weaponcrafting XP required to level up the skill.'
        },
        gearcrafting_level: {
            type: 'integer',
            title: 'Gearcrafting Level',
            description: 'Gearcrafting level.'
        },
        gearcrafting_xp: {
            type: 'integer',
            title: 'Gearcrafting Xp',
            description: 'The current xp level of the Gearcrafting skill.'
        },
        gearcrafting_max_xp: {
            type: 'integer',
            title: 'Gearcrafting Max Xp',
            description: 'Gearcrafting XP required to level up the skill.'
        },
        jewelrycrafting_level: {
            type: 'integer',
            title: 'Jewelrycrafting Level',
            description: 'Jewelrycrafting level.'
        },
        jewelrycrafting_xp: {
            type: 'integer',
            title: 'Jewelrycrafting Xp',
            description: 'The current xp level of the Jewelrycrafting skill.'
        },
        jewelrycrafting_max_xp: {
            type: 'integer',
            title: 'Jewelrycrafting Max Xp',
            description: 'Jewelrycrafting XP required to level up the skill.'
        },
        cooking_level: {
            type: 'integer',
            title: 'Cooking Level',
            description: 'The current xp level of the Cooking skill.'
        },
        cooking_xp: {
            type: 'integer',
            title: 'Cooking Xp',
            description: 'Cooking XP.'
        },
        cooking_max_xp: {
            type: 'integer',
            title: 'Cooking Max Xp',
            description: 'Cooking XP required to level up the skill.'
        },
        hp: {
            type: 'integer',
            title: 'Hp',
            description: 'Character HP.'
        },
        haste: {
            type: 'integer',
            title: 'Haste',
            description: '*Character Haste. Increase speed attack (reduce fight cooldown)'
        },
        critical_strike: {
            type: 'integer',
            title: 'Critical Strike',
            description: "*Not available, on the roadmap. Character Critical   Strike. Critical strikes increase the attack's damage."
        },
        stamina: {
            type: 'integer',
            title: 'Stamina',
            description: '*Not available, on the roadmap. Regenerates life at the start of each turn.'
        },
        attack_fire: {
            type: 'integer',
            title: 'Attack Fire',
            description: 'Fire attack.'
        },
        attack_earth: {
            type: 'integer',
            title: 'Attack Earth',
            description: 'Earth attack.'
        },
        attack_water: {
            type: 'integer',
            title: 'Attack Water',
            description: 'Water attack.'
        },
        attack_air: {
            type: 'integer',
            title: 'Attack Air',
            description: 'Air attack.'
        },
        dmg_fire: {
            type: 'integer',
            title: 'Dmg Fire',
            description: '% Fire damage.'
        },
        dmg_earth: {
            type: 'integer',
            title: 'Dmg Earth',
            description: '% Earth damage.'
        },
        dmg_water: {
            type: 'integer',
            title: 'Dmg Water',
            description: '% Water damage.'
        },
        dmg_air: {
            type: 'integer',
            title: 'Dmg Air',
            description: '% Air damage.'
        },
        res_fire: {
            type: 'integer',
            title: 'Res Fire',
            description: '% Fire resistance.'
        },
        res_earth: {
            type: 'integer',
            title: 'Res Earth',
            description: '% Earth resistance.'
        },
        res_water: {
            type: 'integer',
            title: 'Res Water',
            description: '% Water resistance.'
        },
        res_air: {
            type: 'integer',
            title: 'Res Air',
            description: '% Air resistance.'
        },
        x: {
            type: 'integer',
            title: 'X',
            description: 'Character x coordinate.'
        },
        y: {
            type: 'integer',
            title: 'Y',
            description: 'Character y coordinate.'
        },
        cooldown: {
            type: 'integer',
            title: 'Cooldown',
            description: 'Cooldown in seconds.'
        },
        cooldown_expiration: {
            type: 'string',
            format: 'date-time',
            title: 'Cooldown Expiration',
            description: 'Datetime Cooldown expiration.'
        },
        weapon_slot: {
            type: 'string',
            title: 'Weapon Slot',
            description: 'Weapon slot.'
        },
        shield_slot: {
            type: 'string',
            title: 'Shield Slot',
            description: 'Shield slot.'
        },
        helmet_slot: {
            type: 'string',
            title: 'Helmet Slot',
            description: 'Helmet slot.'
        },
        body_armor_slot: {
            type: 'string',
            title: 'Body Armor Slot',
            description: 'Body armor slot.'
        },
        leg_armor_slot: {
            type: 'string',
            title: 'Leg Armor Slot',
            description: 'Leg armor slot.'
        },
        boots_slot: {
            type: 'string',
            title: 'Boots Slot',
            description: 'Boots slot.'
        },
        ring1_slot: {
            type: 'string',
            title: 'Ring1 Slot',
            description: 'Ring 1 slot.'
        },
        ring2_slot: {
            type: 'string',
            title: 'Ring2 Slot',
            description: 'Ring 2 slot.'
        },
        amulet_slot: {
            type: 'string',
            title: 'Amulet Slot',
            description: 'Amulet slot.'
        },
        artifact1_slot: {
            type: 'string',
            title: 'Artifact1 Slot',
            description: 'Artifact 1 slot.'
        },
        artifact2_slot: {
            type: 'string',
            title: 'Artifact2 Slot',
            description: 'Artifact 2 slot.'
        },
        artifact3_slot: {
            type: 'string',
            title: 'Artifact3 Slot',
            description: 'Artifact 3 slot.'
        },
        consumable1_slot: {
            type: 'string',
            title: 'Consumable1 Slot',
            description: 'Consumable 1 slot.'
        },
        consumable1_slot_quantity: {
            type: 'integer',
            title: 'Consumable1 Slot Quantity',
            description: 'Consumable 1 quantity.'
        },
        consumable2_slot: {
            type: 'string',
            title: 'Consumable2 Slot',
            description: 'Consumable 2 slot.'
        },
        consumable2_slot_quantity: {
            type: 'integer',
            title: 'Consumable2 Slot Quantity',
            description: 'Consumable 2 quantity.'
        },
        task: {
            type: 'string',
            title: 'Task',
            description: 'Task in progress.'
        },
        task_type: {
            type: 'string',
            title: 'Task Type',
            description: 'Task type.'
        },
        task_progress: {
            type: 'integer',
            title: 'Task Progress',
            description: 'Task progression.'
        },
        task_total: {
            type: 'integer',
            title: 'Task Total',
            description: 'Task total objective.'
        },
        inventory_max_items: {
            type: 'integer',
            title: 'Inventory Max Items',
            description: 'Inventory max items.'
        },
        inventory: {
            items: {
                '$ref': '#/components/schemas/InventorySlot'
            },
            type: 'array',
            title: 'Inventory',
            description: 'List of inventory slots.'
        }
    },
    type: 'object',
    required: ['name', 'skin', 'level', 'xp', 'max_xp', 'achievements_points', 'gold', 'speed', 'mining_level', 'mining_xp', 'mining_max_xp', 'woodcutting_level', 'woodcutting_xp', 'woodcutting_max_xp', 'fishing_level', 'fishing_xp', 'fishing_max_xp', 'weaponcrafting_level', 'weaponcrafting_xp', 'weaponcrafting_max_xp', 'gearcrafting_level', 'gearcrafting_xp', 'gearcrafting_max_xp', 'jewelrycrafting_level', 'jewelrycrafting_xp', 'jewelrycrafting_max_xp', 'cooking_level', 'cooking_xp', 'cooking_max_xp', 'hp', 'haste', 'critical_strike', 'stamina', 'attack_fire', 'attack_earth', 'attack_water', 'attack_air', 'dmg_fire', 'dmg_earth', 'dmg_water', 'dmg_air', 'res_fire', 'res_earth', 'res_water', 'res_air', 'x', 'y', 'cooldown', 'weapon_slot', 'shield_slot', 'helmet_slot', 'body_armor_slot', 'leg_armor_slot', 'boots_slot', 'ring1_slot', 'ring2_slot', 'amulet_slot', 'artifact1_slot', 'artifact2_slot', 'artifact3_slot', 'consumable1_slot', 'consumable1_slot_quantity', 'consumable2_slot', 'consumable2_slot_quantity', 'task', 'task_type', 'task_progress', 'task_total', 'inventory_max_items'],
    title: 'CharacterSchema'
} as const;

export const $CooldownSchema = {
    properties: {
        total_seconds: {
            type: 'integer',
            title: 'Total Seconds',
            description: 'The total seconds of the cooldown.'
        },
        remaining_seconds: {
            type: 'integer',
            title: 'Remaining Seconds',
            description: 'The remaining seconds of the cooldown.'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At',
            description: 'The start of the cooldown.'
        },
        expiration: {
            type: 'string',
            format: 'date-time',
            title: 'Expiration',
            description: 'The expiration of the cooldown.'
        },
        reason: {
            type: 'string',
            enum: ['movement', 'fight', 'crafting', 'gathering', 'buy_ge', 'sell_ge', 'delete_item', 'deposit_bank', 'withdraw_bank', 'equip', 'unequip', 'task', 'recycling'],
            title: 'Reason',
            description: 'The reason of the cooldown.'
        }
    },
    type: 'object',
    required: ['total_seconds', 'remaining_seconds', 'started_at', 'expiration', 'reason'],
    title: 'CooldownSchema'
} as const;

export const $CraftSchema = {
    properties: {
        skill: {
            type: 'string',
            enum: ['weaponcrafting', 'gearcrafting', 'jewelrycrafting', 'cooking', 'woodcutting', 'mining'],
            title: 'Skill code',
            description: 'Skill required to craft the item.'
        },
        level: {
            type: 'integer',
            title: 'Level',
            description: 'The skill level required to craft the item.'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/SimpleItemSchema'
            },
            type: 'array',
            title: 'Items',
            description: 'List of items required to craft the item.'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity',
            description: 'Quantity of items crafted.'
        }
    },
    type: 'object',
    title: 'CraftSchema'
} as const;

export const $CraftingSchema = {
    properties: {
        code: {
            type: 'string',
            pattern: '^[a-zA-Z0-9_-]+$',
            title: 'Craft code',
            description: 'Craft code.'
        },
        quantity: {
            type: 'integer',
            minimum: 1,
            title: 'Quantity',
            description: 'Quantity of items to craft.',
            default: 1
        }
    },
    type: 'object',
    required: ['code'],
    title: 'CraftingSchema'
} as const;

export const $DataPage_AchievementSchema_ = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AchievementSchema'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'size'],
    title: 'DataPage[AchievementSchema]'
} as const;

export const $DataPage_ActiveEventSchema_ = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ActiveEventSchema'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'size'],
    title: 'DataPage[ActiveEventSchema]'
} as const;

export const $DataPage_BaseAchievementSchema_ = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BaseAchievementSchema'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'size'],
    title: 'DataPage[BaseAchievementSchema]'
} as const;

export const $DataPage_CharacterLeaderboardSchema_ = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CharacterLeaderboardSchema'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'size'],
    title: 'DataPage[CharacterLeaderboardSchema]'
} as const;

export const $DataPage_CharacterSchema_ = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CharacterSchema'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'size'],
    title: 'DataPage[CharacterSchema]'
} as const;

export const $DataPage_GEItemSchema_ = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GEItemSchema'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'size'],
    title: 'DataPage[GEItemSchema]'
} as const;

export const $DataPage_ItemSchema_ = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemSchema'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'size'],
    title: 'DataPage[ItemSchema]'
} as const;

export const $DataPage_LogSchema_ = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LogSchema'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'size'],
    title: 'DataPage[LogSchema]'
} as const;

export const $DataPage_MapSchema_ = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MapSchema'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'size'],
    title: 'DataPage[MapSchema]'
} as const;

export const $DataPage_MonsterSchema_ = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MonsterSchema'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'size'],
    title: 'DataPage[MonsterSchema]'
} as const;

export const $DataPage_ResourceSchema_ = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ResourceSchema'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'size'],
    title: 'DataPage[ResourceSchema]'
} as const;

export const $DataPage_SimpleItemSchema_ = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SimpleItemSchema'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'size'],
    title: 'DataPage[SimpleItemSchema]'
} as const;

export const $DeleteCharacterSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 12,
            minLength: 3,
            pattern: '^[a-zA-Z0-9_-]+$',
            title: 'Name',
            description: 'Character name.'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DeleteCharacterSchema'
} as const;

export const $DeleteItemResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/DeleteItemSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'DeleteItemResponseSchema'
} as const;

export const $DeleteItemSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details.'
        },
        item: {
            allOf: [
                {
                    '$ref': '#/components/schemas/SimpleItemSchema'
                }
            ],
            description: 'Item details.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Player details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'item', 'character'],
    title: 'DeleteItemSchema'
} as const;

export const $DepositWithdrawGoldSchema = {
    properties: {
        quantity: {
            type: 'integer',
            minimum: 1,
            title: 'Quantity',
            description: 'Quantity of gold.'
        }
    },
    type: 'object',
    required: ['quantity'],
    title: 'DepositWithdrawGoldSchema'
} as const;

export const $DestinationSchema = {
    properties: {
        x: {
            type: 'integer',
            title: 'X',
            description: 'The x coordinate of the destination.'
        },
        y: {
            type: 'integer',
            title: 'Y',
            description: 'The y coordinate of the destination.'
        }
    },
    type: 'object',
    required: ['x', 'y'],
    title: 'DestinationSchema'
} as const;

export const $DropRateSchema = {
    properties: {
        code: {
            type: 'string',
            pattern: '^[a-zA-Z0-9_-]+$',
            title: 'Item code',
            description: 'Item code.'
        },
        rate: {
            type: 'integer',
            minimum: 1,
            title: 'Rate',
            description: 'Chance rate.'
        },
        min_quantity: {
            type: 'integer',
            minimum: 1,
            title: 'Min Quantity',
            description: 'Minimum quantity.'
        },
        max_quantity: {
            type: 'integer',
            minimum: 1,
            title: 'Max Quantity',
            description: 'Maximum quantity.'
        }
    },
    type: 'object',
    required: ['code', 'rate', 'min_quantity', 'max_quantity'],
    title: 'DropRateSchema'
} as const;

export const $DropSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code',
            description: 'The code of the item.'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity',
            description: 'The quantity of the item.'
        }
    },
    type: 'object',
    required: ['code', 'quantity'],
    title: 'DropSchema'
} as const;

export const $EquipRequestSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details.'
        },
        slot: {
            type: 'string',
            enum: ['weapon', 'shield', 'helmet', 'body_armor', 'leg_armor', 'boots', 'ring1', 'ring2', 'amulet', 'artifact1', 'artifact2', 'artifact3', 'consumable1', 'consumable2'],
            title: 'Slot',
            description: 'Item slot.'
        },
        item: {
            allOf: [
                {
                    '$ref': '#/components/schemas/ItemSchema'
                }
            ],
            description: 'Item details.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Player details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'slot', 'item', 'character'],
    title: 'EquipRequestSchema'
} as const;

export const $EquipSchema = {
    properties: {
        code: {
            type: 'string',
            pattern: '^[a-zA-Z0-9_-]+$',
            title: 'Code',
            description: 'Item code.'
        },
        slot: {
            type: 'string',
            enum: ['weapon', 'shield', 'helmet', 'body_armor', 'leg_armor', 'boots', 'ring1', 'ring2', 'amulet', 'artifact1', 'artifact2', 'artifact3', 'consumable1', 'consumable2'],
            title: 'Slot',
            description: 'Item slot.'
        },
        quantity: {
            type: 'integer',
            maximum: 100,
            title: 'Quantity',
            description: 'Item quantity. Applicable to consumables only.',
            default: 1
        }
    },
    type: 'object',
    required: ['code', 'slot'],
    title: 'EquipSchema'
} as const;

export const $EquipmentResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/EquipRequestSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'EquipmentResponseSchema'
} as const;

export const $FightSchema = {
    properties: {
        xp: {
            type: 'integer',
            title: 'Xp',
            description: 'The amount of xp gained by the fight.'
        },
        gold: {
            type: 'integer',
            title: 'Gold',
            description: 'The amount of gold gained by the fight.'
        },
        drops: {
            items: {
                '$ref': '#/components/schemas/DropSchema'
            },
            type: 'array',
            title: 'Drops',
            description: 'The items dropped by the fight.'
        },
        turns: {
            type: 'integer',
            title: 'Turns',
            description: 'Numbers of the turns of the combat.'
        },
        monster_blocked_hits: {
            allOf: [
                {
                    '$ref': '#/components/schemas/BlockedHitsSchema'
                }
            ],
            description: 'The amount of blocked hits by the monster.'
        },
        player_blocked_hits: {
            allOf: [
                {
                    '$ref': '#/components/schemas/BlockedHitsSchema'
                }
            ],
            description: 'The amount of blocked hits by the player.'
        },
        logs: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Logs',
            description: 'The fight logs.'
        },
        result: {
            type: 'string',
            enum: ['win', 'lose'],
            title: 'Result',
            description: 'The result of the fight.'
        }
    },
    type: 'object',
    required: ['xp', 'gold', 'drops', 'turns', 'monster_blocked_hits', 'player_blocked_hits', 'logs', 'result'],
    title: 'FightSchema'
} as const;

export const $GEItemResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/GEItemSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'GEItemResponseSchema'
} as const;

export const $GEItemSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code',
            description: 'Item code.'
        },
        stock: {
            type: 'integer',
            title: 'Stock',
            description: 'Item stock.'
        },
        sell_price: {
            type: 'integer',
            title: 'Sell Price',
            description: "The item's selling price."
        },
        buy_price: {
            type: 'integer',
            title: 'Buy Price',
            description: "The item's buying price."
        },
        max_quantity: {
            type: 'integer',
            title: 'Max Quantity',
            description: 'The number of items you can buy or sell at the same time.'
        }
    },
    type: 'object',
    required: ['code', 'stock', 'max_quantity'],
    title: 'GEItemSchema'
} as const;

export const $GETransactionItemSchema = {
    properties: {
        code: {
            type: 'string',
            pattern: '^[a-zA-Z0-9_-]+$',
            title: 'Code',
            description: 'Item code.'
        },
        quantity: {
            type: 'integer',
            maximum: 100,
            minimum: 1,
            title: 'Quantity',
            description: 'Item quantity.'
        },
        price: {
            type: 'integer',
            minimum: 1,
            title: 'Price',
            description: 'Item price. Item price validation protects you if the price has changed since you last checked the buy/sale price of an item.'
        }
    },
    type: 'object',
    required: ['code', 'quantity', 'price'],
    title: 'GETransactionItemSchema'
} as const;

export const $GETransactionListSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details.'
        },
        transaction: {
            allOf: [
                {
                    '$ref': '#/components/schemas/GETransactionSchema'
                }
            ],
            description: 'Transaction details.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Character details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'transaction', 'character'],
    title: 'GETransactionListSchema'
} as const;

export const $GETransactionResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/GETransactionListSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'GETransactionResponseSchema'
} as const;

export const $GETransactionSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code',
            description: 'Item code.'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity',
            description: 'Item quantity.'
        },
        price: {
            type: 'integer',
            title: 'Price',
            description: 'Item price.'
        },
        total_price: {
            type: 'integer',
            title: 'Total Price',
            description: 'Total price of the transaction.'
        }
    },
    type: 'object',
    required: ['code', 'quantity', 'price', 'total_price'],
    title: 'GETransactionSchema'
} as const;

export const $GoldSchema = {
    properties: {
        quantity: {
            type: 'integer',
            minimum: 0,
            title: 'Quantity',
            description: 'Quantity of gold.'
        }
    },
    type: 'object',
    required: ['quantity'],
    title: 'GoldSchema'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $InventorySlot = {
    properties: {
        slot: {
            type: 'integer',
            title: 'Slot',
            description: 'Inventory slot identifier.'
        },
        code: {
            type: 'string',
            title: 'Code',
            description: 'Item code.'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity',
            description: 'Quantity in the slot.'
        }
    },
    type: 'object',
    required: ['slot', 'code', 'quantity'],
    title: 'InventorySlot'
} as const;

export const $ItemEffectSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Effect name.'
        },
        value: {
            type: 'integer',
            title: 'Value',
            description: 'Effect value.'
        }
    },
    type: 'object',
    required: ['name', 'value'],
    title: 'ItemEffectSchema'
} as const;

export const $ItemResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/SingleItemSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ItemResponseSchema'
} as const;

export const $ItemSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Item name.'
        },
        code: {
            type: 'string',
            title: 'Code',
            description: "Item code. This is the item's unique identifier (ID)."
        },
        level: {
            type: 'integer',
            minimum: 1,
            title: 'Level',
            description: 'Item level.'
        },
        type: {
            type: 'string',
            title: 'Type',
            description: 'Item type.'
        },
        subtype: {
            type: 'string',
            title: 'Subtype',
            description: 'Item subtype.'
        },
        description: {
            type: 'string',
            title: 'Description',
            description: 'Item description.'
        },
        effects: {
            items: {
                '$ref': '#/components/schemas/ItemEffectSchema'
            },
            type: 'array',
            title: 'Effects',
            description: 'List of object effects. For equipment, it will include item stats.'
        },
        craft: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CraftSchema'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Craft information. If applicable.'
        }
    },
    type: 'object',
    required: ['name', 'code', 'level', 'type', 'subtype', 'description'],
    title: 'ItemSchema'
} as const;

export const $LogSchema = {
    properties: {
        character: {
            type: 'string',
            title: 'Character',
            description: 'Character name.'
        },
        account: {
            type: 'string',
            title: 'Account',
            description: 'Account character.'
        },
        type: {
            type: 'string',
            title: 'Type',
            description: 'Type of action.'
        },
        description: {
            type: 'string',
            title: 'Description',
            description: 'Description of action.'
        },
        content: {
            title: 'Content',
            description: 'Content of action.'
        },
        cooldown: {
            type: 'integer',
            title: 'Cooldown',
            description: 'Cooldown in seconds.'
        },
        cooldown_expiration: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooldown Expiration',
            description: 'Datetime of cooldown expiration.'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: 'Datetime of creation.'
        }
    },
    type: 'object',
    required: ['character', 'account', 'type', 'description', 'content', 'cooldown', 'cooldown_expiration', 'created_at'],
    title: 'LogSchema'
} as const;

export const $MapContentSchema = {
    properties: {
        type: {
            type: 'string',
            title: 'Type',
            description: 'Type of the content.'
        },
        code: {
            type: 'string',
            title: 'Code',
            description: 'Code of the content.'
        }
    },
    type: 'object',
    required: ['type', 'code'],
    title: 'MapContentSchema'
} as const;

export const $MapResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/MapSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'MapResponseSchema'
} as const;

export const $MapSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Name of the map.'
        },
        skin: {
            type: 'string',
            title: 'Skin',
            description: 'Skin of the map.'
        },
        x: {
            type: 'integer',
            title: 'X',
            description: 'Position X of the map.'
        },
        y: {
            type: 'integer',
            title: 'Y',
            description: 'Position Y of the map.'
        },
        content: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MapContentSchema'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Content of the map.'
        }
    },
    type: 'object',
    required: ['name', 'skin', 'x', 'y', 'content'],
    title: 'MapSchema'
} as const;

export const $MonsterResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/MonsterSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'MonsterResponseSchema'
} as const;

export const $MonsterSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Name of the monster.'
        },
        code: {
            type: 'string',
            title: 'Code',
            description: "The code of the monster. This is the monster's unique identifier (ID)."
        },
        level: {
            type: 'integer',
            title: 'Level',
            description: 'Monster level.'
        },
        hp: {
            type: 'integer',
            title: 'Hp',
            description: 'Monster hit points.'
        },
        attack_fire: {
            type: 'integer',
            title: 'Attack Fire',
            description: 'Monster fire attack.'
        },
        attack_earth: {
            type: 'integer',
            title: 'Attack Earth',
            description: 'Monster earth attack.'
        },
        attack_water: {
            type: 'integer',
            title: 'Attack Water',
            description: 'Monster water attack.'
        },
        attack_air: {
            type: 'integer',
            title: 'Attack Air',
            description: 'Monster air attack.'
        },
        res_fire: {
            type: 'integer',
            title: 'Res Fire',
            description: 'Monster % fire resistance.'
        },
        res_earth: {
            type: 'integer',
            title: 'Res Earth',
            description: 'Monster % earth resistance.'
        },
        res_water: {
            type: 'integer',
            title: 'Res Water',
            description: 'Monster % water resistance.'
        },
        res_air: {
            type: 'integer',
            title: 'Res Air',
            description: 'Monster % air resistance.'
        },
        min_gold: {
            type: 'integer',
            title: 'Min Gold',
            description: 'Monster minimum gold drop. '
        },
        max_gold: {
            type: 'integer',
            title: 'Max Gold',
            description: 'Monster maximum gold drop. '
        },
        drops: {
            items: {
                '$ref': '#/components/schemas/DropRateSchema'
            },
            type: 'array',
            title: 'Drops',
            description: 'Monster drops. This is a list of items that the monster drops after killing the monster. '
        }
    },
    type: 'object',
    required: ['name', 'code', 'level', 'hp', 'attack_fire', 'attack_earth', 'attack_water', 'attack_air', 'res_fire', 'res_earth', 'res_water', 'res_air', 'min_gold', 'max_gold', 'drops'],
    title: 'MonsterSchema'
} as const;

export const $MyCharactersListSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CharacterSchema'
            },
            type: 'array',
            title: 'Data',
            description: 'List of your characters.'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'MyCharactersListSchema'
} as const;

export const $RecyclingDataSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details.'
        },
        details: {
            allOf: [
                {
                    '$ref': '#/components/schemas/RecyclingItemsSchema'
                }
            ],
            description: 'Craft details.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Player details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'details', 'character'],
    title: 'RecyclingDataSchema'
} as const;

export const $RecyclingItemsSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/DropSchema'
            },
            type: 'array',
            title: 'Items',
            description: 'Objects received.'
        }
    },
    type: 'object',
    required: ['items'],
    title: 'RecyclingItemsSchema'
} as const;

export const $RecyclingResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/RecyclingDataSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'RecyclingResponseSchema'
} as const;

export const $RecyclingSchema = {
    properties: {
        code: {
            type: 'string',
            pattern: '^[a-zA-Z0-9_-]+$',
            title: 'Item code',
            description: 'Item code.'
        },
        quantity: {
            type: 'integer',
            minimum: 1,
            title: 'Quantity',
            description: 'Quantity of items to recycle.',
            default: 1
        }
    },
    type: 'object',
    required: ['code'],
    title: 'RecyclingSchema'
} as const;

export const $ResourceResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/ResourceSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ResourceResponseSchema'
} as const;

export const $ResourceSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'The name of the resource'
        },
        code: {
            type: 'string',
            title: 'Code',
            description: "The code of the resource. This is the resource's unique identifier (ID)."
        },
        skill: {
            type: 'string',
            enum: ['mining', 'woodcutting', 'fishing'],
            title: 'Skill code',
            description: 'The skill required to gather this resource.'
        },
        level: {
            type: 'integer',
            title: 'Level',
            description: 'The skill level required to gather this resource.'
        },
        drops: {
            items: {
                '$ref': '#/components/schemas/DropRateSchema'
            },
            type: 'array',
            title: 'Drops',
            description: 'The drops of this resource.'
        }
    },
    type: 'object',
    required: ['name', 'code', 'skill', 'level', 'drops'],
    title: 'ResourceSchema'
} as const;

export const $ResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ResponseSchema'
} as const;

export const $SimpleItemSchema = {
    properties: {
        code: {
            type: 'string',
            pattern: '^[a-zA-Z0-9_-]+$',
            title: 'Code',
            description: 'Item code.'
        },
        quantity: {
            type: 'integer',
            minimum: 1,
            title: 'Quantity',
            description: 'Item quantity.'
        }
    },
    type: 'object',
    required: ['code', 'quantity'],
    title: 'SimpleItemSchema'
} as const;

export const $SingleItemSchema = {
    properties: {
        item: {
            allOf: [
                {
                    '$ref': '#/components/schemas/ItemSchema'
                }
            ],
            description: 'Item information.'
        },
        ge: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/GEItemSchema'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Grand Exchange information. If applicable.'
        }
    },
    type: 'object',
    required: ['item'],
    title: 'SingleItemSchema'
} as const;

export const $SkillDataSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details.'
        },
        details: {
            allOf: [
                {
                    '$ref': '#/components/schemas/SkillInfoSchema'
                }
            ],
            description: 'Craft details.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Player details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'details', 'character'],
    title: 'SkillDataSchema'
} as const;

export const $SkillInfoSchema = {
    properties: {
        xp: {
            type: 'integer',
            title: 'Xp',
            description: 'The amount of xp gained.'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/DropSchema'
            },
            type: 'array',
            title: 'Items',
            description: 'Objects received.'
        }
    },
    type: 'object',
    required: ['xp', 'items'],
    title: 'SkillInfoSchema'
} as const;

export const $SkillResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/SkillDataSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'SkillResponseSchema'
} as const;

export const $StatusResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/StatusSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'StatusResponseSchema'
} as const;

export const $StatusSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status',
            description: 'Server status'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        max_level: {
            type: 'integer',
            title: 'Max Level',
            description: 'Maximum level.'
        },
        characters_online: {
            type: 'integer',
            title: 'Characters Online',
            description: 'Characters online.'
        },
        server_time: {
            type: 'string',
            format: 'date-time',
            title: 'Server Time',
            description: 'Server time.'
        },
        announcements: {
            items: {
                '$ref': '#/components/schemas/AnnouncementSchema'
            },
            type: 'array',
            title: 'Announcements',
            description: 'Server announcements.'
        },
        last_wipe: {
            type: 'string',
            title: 'Last Wipe',
            description: 'Last server wipe.'
        },
        next_wipe: {
            type: 'string',
            title: 'Next Wipe',
            description: 'Next server wipe.'
        }
    },
    type: 'object',
    required: ['status', 'max_level', 'characters_online', 'server_time', 'announcements', 'last_wipe', 'next_wipe'],
    title: 'StatusSchema'
} as const;

export const $TaskCancelledResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/TaskCancelledSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'TaskCancelledResponseSchema'
} as const;

export const $TaskCancelledSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Player details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'character'],
    title: 'TaskCancelledSchema'
} as const;

export const $TaskDataSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details.'
        },
        task: {
            allOf: [
                {
                    '$ref': '#/components/schemas/TaskSchema'
                }
            ],
            description: 'Task details.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Player details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'task', 'character'],
    title: 'TaskDataSchema'
} as const;

export const $TaskResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/TaskDataSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'TaskResponseSchema'
} as const;

export const $TaskRewardDataSchema = {
    properties: {
        cooldown: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CooldownSchema'
                }
            ],
            description: 'Cooldown details.'
        },
        reward: {
            allOf: [
                {
                    '$ref': '#/components/schemas/TaskRewardSchema'
                }
            ],
            description: 'Reward details.'
        },
        character: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CharacterSchema'
                }
            ],
            description: 'Player details.'
        }
    },
    type: 'object',
    required: ['cooldown', 'reward', 'character'],
    title: 'TaskRewardDataSchema'
} as const;

export const $TaskRewardResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/TaskRewardDataSchema'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'TaskRewardResponseSchema'
} as const;

export const $TaskRewardSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code',
            description: 'Item code.'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity',
            description: 'Item quantity.'
        }
    },
    type: 'object',
    required: ['code', 'quantity'],
    title: 'TaskRewardSchema'
} as const;

export const $TaskSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code',
            description: 'Task objective.'
        },
        type: {
            type: 'string',
            enum: ['monsters', 'resources', 'crafts'],
            title: 'Type',
            description: 'The type of task.'
        },
        total: {
            type: 'integer',
            title: 'Total',
            description: 'The total required to complete the task.'
        }
    },
    type: 'object',
    required: ['code', 'type', 'total'],
    title: 'TaskSchema'
} as const;

export const $TokenResponseSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        }
    },
    type: 'object',
    required: ['token'],
    title: 'TokenResponseSchema'
} as const;

export const $UnequipSchema = {
    properties: {
        slot: {
            type: 'string',
            enum: ['weapon', 'shield', 'helmet', 'body_armor', 'leg_armor', 'boots', 'ring1', 'ring2', 'amulet', 'artifact1', 'artifact2', 'artifact3', 'consumable1', 'consumable2'],
            title: 'Slot',
            description: 'Item slot.'
        },
        quantity: {
            type: 'integer',
            maximum: 100,
            title: 'Quantity',
            description: 'Item quantity. Applicable to consumables only.',
            default: 1
        }
    },
    type: 'object',
    required: ['slot'],
    title: 'UnequipSchema'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;